### PR TITLE
Filesets to swap

### PR DESCRIPTION
**Pull request by will-moore**
Starting with the list of projects/screens from https://docs.google.com/spreadsheets/d/11Eg8JzY7dqRUMGVAjGIfTcGDs0BitJQJQ20BVoaiZOg/edit#gid=1516505897
and the script `get_filesets_to_swap.py` produced a list of 2062 Filesets (see `idr_filesets.csv`).

Following workflow at https://github.com/IDR/omero-mkngff/issues/2, we harvest the Fileset names and UUIDs from BioStudies, and run `python parse_bia_uuids.py idr0051` script from this PR to add the Fileset IDs based on their name from the `idr_filesets.csv` table created above.

The output `idr00XX.csv` tables are included in this PR.

They are used as the input for `omero mkngff sql` which generated sql outputs. They are also included in this PR.

We could move the `idr00XX.csv` files and the `sql` scripts to a different repo. Don't know if/where we want to document the usage instructions/workflow above?

### CODE REVIEW

**Comment by will-moore** [comment]
Validating `.sql` files to check:
 - We aren't missing `.zarray` files (due to temp `mkngff` bug). 
```
$ for i in $(ls ./); do echo "$i $(grep -c 'zarray' $i)"; done;
```
- There is just 1 "UPDATE" string in each
```
$ for i in $(ls ./); do echo "$i $(grep -c 'UPDATE' $i)"; done;
```
- Remove all `Directory` rows. See https://github.com/IDR/omero-mkngff/issues/2#issuecomment-1729884918 (NB: `sed` doesn't work on Mac, use grep instead):
```
for i in $(ls ./); do grep -v "Directory" $i > temp.txt && mv temp.txt $i ; done;
```

**Comment by will-moore** [comment]
On idr0138-pilot - checked-out this branch and

```
cd /idr-utils/scripts/ngff_filesets/idr0004
```

Got SECRET and as wmoore user (with sudo)
```
for i in $(ls); do sudo sed -i 's/SECRETUUID/fc5d3566-eea0-412c-849e-daa6d3c6bfcc/g' $i; done
```

Then as `omero-server` in `/idr-utils/scripts/ngff_filesets/`...

```
 bash-4.2$ for r in $(cat $IDRID.csv); do
>   biapath=$(echo $r | cut -d',' -f2)
>   uuid=$(echo $biapath | cut -d'/' -f2)
>   fsid=$(echo $r | cut -d',' -f3 | tr -d '[:space:]')
>   psql -U omero -d idr -h $DBHOST -f "$IDRID/$fsid.sql"
>   omero mkngff symlink /data/OMERO/ManagedRepository $fsid "/bia-integrator-data/$biapath/$uuid.zarr"
> done
UPDATE 95
BEGIN
 mkngff_fileset 
----------------
        5811653
(1 row)

COMMIT
Using session for demo@localhost:4064. Idle timeout: 10 min. Current group: Public
Checking for prefix_dir /data/OMERO/ManagedRepository/demo_2/2015-10/01/08-49-38.885
Creating dir at /data/OMERO/ManagedRepository/demo_2/2015-10/01/08-49-38.885_mkngff
Creating symlink /data/OMERO/ManagedRepository/demo_2/2015-10/01/08-49-38.885_mkngff/00d88a93-8d21-4a50-b8b5-60f11bcae0d3.zarr -> /bia-integrator-data/S-BIAD867/00d88a93-8d21-4a50-b8b5-60f11bcae0d3/00d88a93-8d21-4a50-b8b5-60f11bcae0d3.zarr
UPDATE 98
BEGIN
 mkngff_fileset 
----------------
        5811654
(1 row)

COMMIT
...
```

Updated OMEZarrReader.jar on idr0138 to use merge-ci build from 25th September.

But http://localhost:1040/webclient/?show=well-469100 has...
```
    serverExceptionClass = ome.conditions.ResourceError
    message = Error instantiating pixel buffer: /data/OMERO/ManagedRepository/demo_2/2015-10/01/07-25-30.185_mkngff/103d9428-b86b-4f4e-84d8-966b5d89aae1.zarr/.zattrs
```
Symlink looks good...
```
$ ls -alh /data/OMERO/ManagedRepository/demo_2/2015-10/01/07-25-30.185_mkngff/103d9428-b86b-4f4e-84d8-966b5d89aae1.zarr/
total 51K
drwxr-xr-x. 2 root root 4.0K Sep  4 20:44 .
drwxr-xr-x. 2 root root 4.0K Sep 27 05:31 ..
drwxr-xr-x. 2 root root 4.0K Sep  4 20:43 A
drwxr-xr-x. 2 root root 4.0K Sep  4 20:43 B
drwxr-xr-x. 2 root root 4.0K Sep  4 20:44 C
drwxr-xr-x. 2 root root 4.0K Sep  4 20:44 D
drwxr-xr-x. 2 root root 4.0K Sep  4 20:44 E
drwxr-xr-x. 2 root root 4.0K Sep  4 20:44 F
drwxr-xr-x. 2 root root 4.0K Sep  4 20:44 G
drwxr-xr-x. 2 root root 4.0K Sep  4 20:44 H
-rw-r--r--. 1 root root 9.8K Sep  4 20:43 .zattrs
-rw-r--r--. 1 root root   24 Sep  4 20:43 .zgroup
```

Bit of Blitz.log
```
 ome.services.util.ServiceHandler] (l.Server-4)  Args:    [null, InternalSF@1358286427]
2023-09-27 14:02:55,853 INFO  [         ome.security.basic.EventHandler] (l.Server-4)  Auth:    user=52,group=3,event=null(User),sess=5d9cf96c-62a4-46b7-b791-acb7a111e68d
2023-09-27 14:02:55,854 INFO  [                 org.perf4j.TimingLogger] (l.Server-4) start[1695823375851] time[2] tag[omero.call.success.ome.services.blitz.impl.ServiceFactoryI$3.doWork]
2023-09-27 14:02:55,854 INFO  [        ome.services.util.ServiceHandler] (l.Server-4)  Rslt:    false
2023-09-27 14:02:55,855 INFO  [                      omero.cmd.SessionI] (l.Server-4) Added servant to adapter: 5d9cf96c-62a4-46b7-b791-acb7a111e68d/e5237bef-763f-4775-8c70-8645715d8bacomero.api.IContainer(omero.api._IContainerTie@385f9e45)
2023-09-27 14:02:55,857 INFO  [        ome.services.util.ServiceHandler] (l.Server-9)  Meth:    interface ome.api.IContainer.getCollectionCount
2023-09-27 14:02:55,857 INFO  [        ome.services.util.ServiceHandler] (l.Server-9)  Args:    [ome.model.screen.Screen, plateLinks, (1201), null]
2023-09-27 14:02:55,857 INFO  [    ome.security.basic.BasicEventContext] (l.Server-9)  cctx:    group=-1
2023-09-27 14:02:55,860 INFO  [         ome.security.basic.EventHandler] (l.Server-9)  Auth:    user=52,group=-1,event=null(User),sess=5d9cf96c-62a4-46b7-b791-acb7a111e68d
2023-09-27 14:02:55,862 INFO  [                 org.perf4j.TimingLogger] (l.Server-9) start[1695823375857] time[5] tag[omero.call.success.ome.logic.PojosImpl.getCollectionCount]
2023-09-27 14:02:55,862 INFO  [        ome.services.util.ServiceHandler] (l.Server-9)  Rslt:    {1201=84}
2023-09-27 14:02:55,865 INFO  [        ome.services.util.ServiceHandler] (l.Server-1)  Meth:    interface ome.api.IContainer.getCollectionCount
2023-09-27 14:02:55,865 INFO  [        ome.services.util.ServiceHandler] (l.Server-1)  Args:    [ome.model.screen.Screen, plateLinks, (1201), null]
2023-09-27 14:02:55,866 INFO  [    ome.security.basic.BasicEventContext] (l.Server-1)  cctx:    group=-1
2023-09-27 14:02:55,869 INFO  [         ome.security.basic.EventHandler] (l.Server-1)  Auth:    user=52,group=-1,event=null(User),sess=5d9cf96c-62a4-46b7-b791-acb7a111e68d
2023-09-27 14:02:55,871 INFO  [                 org.perf4j.TimingLogger] (l.Server-1) start[1695823375865] time[5] tag[omero.call.success.ome.logic.PojosImpl.getCollectionCount]
2023-09-27 14:02:55,871 INFO  [        ome.services.util.ServiceHandler] (l.Server-1)  Rslt:    {1201=84}
2023-09-27 14:02:55,877 INFO  [o.services.sessions.SessionContext$Count] (l.Server-5) -Reference count: 5d9cf96c-62a4-46b7-b791-acb7a111e68d=0
2023-09-27 14:02:55,877 INFO  [                      omero.cmd.SessionI] (l.Server-5) cleanupSelf(ServiceFactoryI(session-e5237bef-763f-4775-8c70-8645715d8bac/5d9cf96c-62a4-46b7-b791-acb7a111e68d)).
2023-09-27 14:02:55,877 INFO  [                      omero.cmd.SessionI] (l.Server-5) Unregistered servant:5d9cf96c-62a4-46b7-b791-acb7a111e68d/e5237bef-763f-4775-8c70-8645715d8bacomero.api.IConfig(omero.api._IConfigTie@32786d21)
2023-09-27 14:02:55,877 INFO  [                      omero.cmd.SessionI] (l.Server-5) Removed servant from adapter: e5237bef-763f-4775-8c70-8645715d8bacomero.api.IConfig
2023-09-27 14:02:55,877 INFO  [                      omero.cmd.SessionI] (l.Server-5) Unregistered servant:5d9cf96c-62a4-46b7-b791-acb7a111e68d/e5237bef-763f-4775-8c70-8645715d8bacomero.api.IScript(omero.api._IScriptTie@d34ee24b)
2023-09-27 14:02:55,877 INFO  [                      omero.cmd.SessionI] (l.Server-5) Removed servant from adapter: e5237bef-763f-4775-8c70-8645715d8bacomero.api.IScript
2023-09-27 14:02:55,877 INFO  [                      omero.cmd.SessionI] (l.Server-5) Unregistered servant:5d9cf96c-62a4-46b7-b791-acb7a111e68d/e5237bef-763f-4775-8c70-8645715d8bacomero.api.IContainer(omero.api._IContainerTie@385f9e45)
2023-09-27 14:02:55,877 INFO  [                      omero.cmd.SessionI] (l.Server-5) Removed servant from adapter: e5237bef-763f-4775-8c70-8645715d8bacomero.api.IContainer
2023-09-27 14:02:55,877 INFO  [                      omero.cmd.SessionI] (l.Server-5) Unregistered servant:5d9cf96c-62a4-46b7-b791-acb7a111e68d/e5237bef-763f-4775-8c70-8645715d8bacomero.api.IAdmin(omero.api._IAdminTie@dbd4c287)
2023-09-27 14:02:55,877 INFO  [                      omero.cmd.SessionI] (l.Server-5) Removed servant from adapter: e5237bef-763f-4775-8c70-8645715d8bacomero.api.IAdmin
2023-09-27 14:02:55,877 INFO  [                      omero.cmd.SessionI] (l.Server-5) Unregistered servant:5d9cf96c-62a4-46b7-b791-acb7a111e68d/e5237bef-763f-4775-8c70-8645715d8bacomero.api.IQuery(omero.api._IQueryTie@2b372059)
2023-09-27 14:02:55,877 INFO  [                      omero.cmd.SessionI] (l.Server-5) Removed servant from adapter: e5237bef-763f-4775-8c70-8645715d8bacomero.api.IQuery
2023-09-27 14:02:56,716 ERROR [              loci.formats.FormatHandler] (l.Server-3) ZarrReader attempting to generate Array Keys
2023-09-27 14:02:56,819 ERROR [              loci.formats.FormatHandler] (l.Server-3) Skipping array path as sparse data: A/1/0/0
2023-09-27 14:02:56,932 ERROR [              loci.formats.FormatHandler] (l.Server-3) Skipping array path as sparse data: A/1/0/1
2023-09-27 14:02:57,037 ERROR [              loci.formats.FormatHandler] (l.Server-3) Skipping array path as sparse data: A/1/0/2
2023-09-27 14:02:57,213 ERROR [              loci.formats.FormatHandler] (l.Server-3) Skipping array path as sparse data: A/1/0/3
2023-09-27 14:03:00,002 INFO  [ ome.services.blitz.fire.SessionManagerI] (2-thread-5) Performing requestHeartbeats
2023-09-27 14:03:00,009 WARN  [ o.services.blitz.fire.TopicManager$Impl] (2-thread-5) Found no topic manager
2023-09-27 14:03:00,009 WARN  [ o.services.blitz.fire.TopicManager$Impl] (2-thread-5) No topic manager
2023-09-27 14:03:01,664 ERROR [              loci.formats.FormatHandler] (l.Server-3) Skipping array path as sparse data: A/11/0/0
2023-09-27 14:03:01,882 ERROR [              loci.formats.FormatHandler] (l.Server-3) Skipping array path as sparse data: A/11/0/1
2023-09-27 14:03:01,985 ERROR [              loci.formats.FormatHandler] (l.Server-3) Skipping array path as sparse data: A/11/0/2
2023-09-27 14:03:02,095 ERROR [              loci.formats.FormatHandler] (l.Server-3) Skipping array path as sparse data: A/11/0/3
2023-09-27 14:03:02,202 ERROR [              loci.formats.FormatHandler] (l.Server-3) Skipping array path as sparse data: A/12/0/0
2023-09-27 14:03:02,267 ERROR [              loci.formats.FormatHandler] (l.Server-3) Skipping array path as sparse data: A/12/0/1
2023-09-27 14:03:02,331 ERROR [              loci.formats.FormatHandler] (l.Server-3) Skipping array path as sparse data: A/12/0/2
2023-09-27 14:03:02,395 ERROR [              loci.formats.FormatHandler] (l.Server-3) Skipping array pa
...
```

**Comment by will-moore** [comment]
```
bash-4.2$ wget https://merge-ci.openmicroscopy.org/jenkins/job/BIOFORMATS-build/553/default/artifact/bio-formats-build/ZarrReader/target/OMEZarrReader-0.3.2-SNAPSHOT-jar-with-dependencies.jar
--2023-09-29 05:59:45--  https://merge-ci.openmicroscopy.org/jenkins/job/BIOFORMATS-build/553/default/artifact/bio-formats-build/ZarrReader/target/OMEZarrReader-0.3.2-SNAPSHOT-jar-with-dependencies.jar
Resolving merge-ci.openmicroscopy.org (merge-ci.openmicroscopy.org)... 134.36.65.248
Connecting to merge-ci.openmicroscopy.org (merge-ci.openmicroscopy.org)|134.36.65.248|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 23216281 (22M) [application/java-archive]
Saving to: ‘OMEZarrReader-0.3.2-SNAPSHOT-jar-with-dependencies.jar’

100%[=========================================================================================================================================================================================>] 23,216,281  13.3MB/s   in 1.7s   

2023-09-29 05:59:47 (13.3 MB/s) - ‘OMEZarrReader-0.3.2-SNAPSHOT-jar-with-dependencies.jar’ saved [23216281/23216281]

bash-4.2$ 
bash-4.2$ mv OMEZarrReader-0.3.2-SNAPSHOT-jar-with-dependencies.jar OMEZarrReader_20230929.jar
bash-4.2$ 
bash-4.2$ rm /opt/omero/server/OMERO.server/lib/client/OMEZarrReader.jar
bash-4.2$ rm /opt/omero/server/OMERO.server/lib/server/OMEZarrReader.jar 
bash-4.2$ cp OMEZarrReader_20230929.jar /opt/omero/server/OMERO.server/lib/client/
bash-4.2$ cp OMEZarrReader_20230929.jar /opt/omero/server/OMERO.server/lib/server/
```

**Comment by will-moore** [comment]
http://localhost:1080/webclient/?show=well-469069 with latest ZarrReader (see above)

```
Caused by: ome.conditions.SecurityViolation: file demo_2/2015-10/01/07-25-30.185_mkngff/103d9428-b86b-4f4e-84d8-966b5d89aae1.zarr/F/7/0/0/0/6/0/0 does not have a unique readable fileset
        at ome.services.blitz.repo.ManagedReaderSecurityCheck.getFilesetId(ManagedReaderSecurityCheck.java:100)
        at ome.services.blitz.repo.ManagedReaderSecurityCheck.assertUsedFilesReadable(ManagedReaderSecurityCheck.java:159)
        at ome.io.nio.PixelsService$3.setId(PixelsService.java:870)
```

**Comment by will-moore** [comment]
Also seeing this error with idr0011 Plate:

```
2023-09-29 09:25:04,276 INFO  [                      omero.cmd.SessionI] (l.Server-9) Removed servant from adapter: 80d14442-5e24-42c8-ad8f-3ba5e247502aomero.api.IContainer
2023-09-29 09:25:09,399 WARN  [   o.s.b.repo.ManagedReaderSecurityCheck] (l.Server-3) file demo_2/2016-07/28/13-56-03.328_mkngff/7f95aba3-cfbf-4ae8-a106-edaa36f5b07f.zarr/F/5/0/1/0/2/7/0/0 does not h
ave a unique readable fileset
2023-09-29 09:25:09,399 DEBUG [                   loci.formats.Memoizer] (l.Server-3) start[1695979417618] time[91780] tag[loci.formats.Memoizer.setId]
2023-09-29 09:25:09,400 ERROR [         ome.io.bioformats.BfPixelBuffer] (l.Server-3) Failed to instantiate BfPixelsWrapper with /data/OMERO/ManagedRepository/demo_2/2016-07/28/13-56-03.328_mkngff/7f
95aba3-cfbf-4ae8-a106-edaa36f5b07f.zarr/OME/METADATA.ome.xml
2023-09-29 09:25:09,401 ERROR [                ome.io.nio.PixelsService] (l.Server-3) Error instantiating pixel buffer: /data/OMERO/ManagedRepository/demo_2/2016-07/28/13-56-03.328_mkngff/7f95aba3-cf
bf-4ae8-a106-edaa36f5b07f.zarr/OME/METADATA.ome.xml
java.lang.RuntimeException: ome.conditions.SecurityViolation: file demo_2/2016-07/28/13-56-03.328_mkngff/7f95aba3-cfbf-4ae8-a106-edaa36f5b07f.zarr/F/5/0/1/0/2/7/0/0 does not have a unique readable fi
leset
        at ome.io.bioformats.BfPixelBuffer.reader(BfPixelBuffer.java:79)
        at ome.io.bioformats.BfPixelBuffer.setSeries(BfPixelBuffer.java:124)
        at ome.io.nio.PixelsService.createBfPixelBuffer(PixelsService.java:898)
```

**Comment by will-moore** [comment]
Idr0025 - Plate 1 has the same error (comes after a long delay - regenerating memo file?):
```
2023-09-29 12:48:51,605 WARN  [   o.s.b.repo.ManagedReaderSecurityCheck] (l.Server-6) file demo_2/2017-03/13/15-19-51.590_mkngff/52304cdf-4eba-4f0a-84b1-690e0d66add9.zarr/A/12/3/0/0/2/0/1/1 does not have a unique readable fileset
2023-09-29 12:48:51,606 DEBUG [                   loci.formats.Memoizer] (l.Server-6) start[1695991165561] time[566044] tag[loci.formats.Memoizer.setId]
2023-09-29 12:48:51,606 ERROR [         ome.io.bioformats.BfPixelBuffer] (l.Server-6) Failed to instantiate BfPixelsWrapper with /data/OMERO/ManagedRepository/demo_2/2017-03/13/15-19-51.590_mkngff/52304cdf-4eba-4f0a-84b1-690e0d66add9.zarr/OME/METADATA.ome.xml
2023-09-29 12:48:51,607 ERROR [                ome.io.nio.PixelsService] (l.Server-6) Error instantiating pixel buffer: /data/OMERO/ManagedRepository/demo_2/2017-03/13/15-19-51.590_mkngff/52304cdf-4eba-4f0a-84b1-690e0d66add9.zarr/OME/METADATA.ome.xml
java.lang.RuntimeException: ome.conditions.SecurityViolation: file demo_2/2017-03/13/15-19-51.590_mkngff/52304cdf-4eba-4f0a-84b1-690e0d66add9.zarr/A/12/3/0/0/2/0/1/1 does not have a unique readable fileset
	at ome.io.bioformats.BfPixelBuffer.reader(BfPixelBuffer.java:79)
	at ome.io.bioformats.BfPixelBuffer.setSeries(BfPixelBuffer.java:124)
	at ome.io.nio.PixelsService.createBfPixelBuffer(PixelsService.java:898)
	at ome.io.nio.PixelsService._getPixelBuffer(PixelsService.java:653)
	at ome.io.nio.PixelsService.getPixelBuffer(PixelsService.java:571)
	at ome.services.RenderingBean$12.doWork(RenderingBean.java:2205)
	at jdk.internal.reflect.GeneratedMethodAccessor341.invoke(Unknown Source)
```
but Plate 3 doesn't!

**Comment by will-moore** [comment]
Same error as above with idr0054 images.

idr0051 images are still original pattern files on idr-testing. Lets update with mkngff to test...

```
$ pwd
/uod/idr/metadata/idr-utils
$ sudo -Es git fetch will
$ sudo -Es git checkout will/filesets_to_swap
```

Just run mkngff sql and create symlinks for 1 image...

```
$ psql -U omero -d idr -h $DBHOST -f 604305.sql 
UPDATE 1
BEGIN
 mkngff_fileset 
----------------
        6312208
(1 row)

COMMIT
```

```
$ omero mkngff symlink /data/OMERO/ManagedRepository 604305 "/bia-integrator-data/S-BIAD815/c49efcfd-e767-4ae5-adbf-299cafd92120/c49efcfd-e767-4ae5-adbf-299cafd92120.zarr"
```

```
$ omero mkngff symlink /data/OMERO/ManagedRepository 604305 "/bia-integrator-data/S-BIAD815/c49efcfd-e767-4ae5-adbf-299cafd92120/c49efcfd-e767-4ae5-adbf-299cafd92120.zarr"
Using session for demo@localhost:4064. Idle timeout: 10 min. Current group: Public
Checking for prefix_dir /data/OMERO/ManagedRepository/demo_2/Blitz-0-Ice.ThreadPool.Server-24/2018-11/26/10-39-10.551
Creating dir at /data/OMERO/ManagedRepository/demo_2/Blitz-0-Ice.ThreadPool.Server-24/2018-11/26/10-39-10.551_mkngff
Creating symlink /data/OMERO/ManagedRepository/demo_2/Blitz-0-Ice.ThreadPool.Server-24/2018-11/26/10-39-10.551_mkngff/c49efcfd-e767-4ae5-adbf-299cafd92120.zarr -> /bia-integrator-data/S-BIAD815/c49efcfd-e767-4ae5-adbf-299cafd92120/c49efcfd-e767-4ae5-adbf-299cafd92120.zarr
```

**Comment by joshmoore** [comment]
@will-moore: the `SecurityViolation` exception is the reason I added all the extra files to the SQL output.

**Comment by will-moore** [comment]
With https://github.com/ome/ZarrReader/pull/58 re-opened etc
merged in https://merge-ci.openmicroscopy.org/jenkins/job/BIOFORMATS-push/635/console
built in https://merge-ci.openmicroscopy.org/jenkins/job/BIOFORMATS-build/558/

This OMEZarrReader.jar (named `OMEZarrReader_b558_p635.jar` on idr-testing:omeroreadwrite)
fixes `SecurityViolation` errors above: e.g. idr0004: http://localhost:1080/webclient/?show=well-469069
and idr0054: http://localhost:1080/webclient/?show=image-4007817

**Comment by will-moore** [comment]
This is now working with the `mkngff` sql *without* `Directories` as created from this PR above: https://github.com/IDR/idr-utils/pull/56#issuecomment-1740879424

Screenshot 2023-10-04 at 13 58 20

**Comment by will-moore** [comment]
Actually, I realise that in the ZarrReader push and build above, there was a merge conflict that excluded [the](https://github.com/ome/ZarrReader/pull/64)

```
2023-10-04 12:19:41,146 [   scc.merge] INFO  Merged PRs:
2023-10-04 12:19:41,146 [   scc.merge] INFO    - PR 58 dgault 'Add new option to list pixels in getUsedFiles'
2023-10-04 12:19:41,146 [   scc.merge] INFO    - PR 62 joshmoore 'Update README.md'
2023-10-04 12:19:41,146 [   scc.merge] INFO    - PR 65 dgault 'Bumping Bio-Formats version to 7.0.0'
2023-10-04 12:19:41,147 [   scc.merge] INFO  
2023-10-04 12:19:41,147 [   scc.merge] INFO  Conflicting PRs (not included):
2023-10-04 12:19:41,147 [   scc.merge] INFO    - PR 64 dgault 'ZarrReader performance improvements'
```

So it's *possible* that the "fix" may have been due to the excluding of that PR rather than the inclusion of https://github.com/ome/ZarrReader/pull/58 ?

**Comment by will-moore** [comment]
With https://merge-ci.openmicroscopy.org/jenkins/job/BIOFORMATS-push/637/ and jar from https://merge-ci.openmicroscopy.org/jenkins/job/BIOFORMATS-build/559/default/artifact/bio-formats-build/ZarrReader/target/
this works with the images above.
That build has `getUsedFiles()` changes merged into https://github.com/ome/ZarrReader/pull/64#commits-pushed-82ac198.

**Comment by will-moore** [comment]
To test clientpath changes, need an original (not edited) Fileset.
Test on `idr0138-pilot`...

Checked-out this PR and updated `idr0090/4053140.sql` with SECRET.
Updated and run `setup.sql` with https://github.com/IDR/omero-mkngff/pull/12
`pip install 'omero-mkngff @ git+https://github.com/will-moore/omero-mkngff@clientpath'`
Then ran `4053140.sql`:

Screenshot 2023-10-16 at 22 10 37

Also used that `omero-mkngff` PR to generate sql and run that
(venv3) (base) [wmoore@pilot-idr0138-omeroreadwrite ~]$ omero mkngff sql 4053141 --clientpath=https://uk1s3.embassy.ebi.ac.uk/bia-integrator-data/S-BIAD852/f12bdada-57eb-4fab-90ef-9655e4106497/f12bdada-57eb-4fab-90ef-9655e4106497.zarr --secret=$SECRET /bia-integrator-data/S-BIAD852/f12bdada-57eb-4fab-90ef-9655e4106497/f12bdada-57eb-4fab-90ef-9655e4106497.zarr > 4053141.sql
and ran that sql as above...

Screenshot 2023-10-16 at 22 33 04

**Comment by sbesson** [comment]
Starting from a clean checkout

```
(base) sbesson@Sebastiens-MacBook-Pro-3 idr-utils % du -csh .
1.1M	.
1.1M	total
(base) sbesson@Sebastiens-MacBook-Pro-3 idr-utils % git fetch origin pull/56/merge
remote: Enumerating objects: 4333, done.
remote: Counting objects: 100% (41/41), done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 4333 (delta 39), reused 28 (delta 28), pack-reused 4292
Receiving objects: 100% (4333/4333), 102.44 MiB | 4.50 MiB/s, done.
Resolving deltas: 100% (3002/3002), done.
From https://github.com/IDR/idr-utils
 * branch            refs/pull/56/merge -> FETCH_HEAD
(base) sbesson@Sebastiens-MacBook-Pro-3 idr-utils % du -csh .                     
113M	.
113M	total
```

Even if the size is still relatively small, a 100x size increase to commit SQL scripts expected to be used once defies a bit the aim of this utility repository from my perspective. My vote would be to either use a separate repository or split each file into the appropriate study repository.

**Comment by will-moore** [comment]
OK, I think I'll move each `idr00XX.csv` and the `sql` scripts to the different study repos once we're done using them (and they're not changing). But while they're still being used and potentially edited, I'll keep working with this PR for convenience.
Also much easier to check them out into one place in one go for running them on idr-next etc while they're still in one branch.

**Comment by francesw** [comment]
Done. https://github.com/IDR/mkngff_upgrade_scripts

**Comment by will-moore** [comment]
moved all contents from this PR to https://github.com/IDR/mkngff_upgrade_scripts . Closing...

**Pull request closed without merging**
